name: CI/CD Pipeline

on:
  push:
    branches:
      - fedeco
  pull_request:
    branches:
      - fedeco

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: TypeScript type check
        run: |
          if [ -f tsconfig.json ]; then
            npx tsc --noEmit
          fi

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build
        if: success()

      # Optional: Add deployment step here
      # - name: Deploy
      #   run: npm run deploy
      #   env:
      #     DEPLOY_API_KEY: ${{ secrets.DEPLOY_API_KEY }}
